### ISSUE TITLE
Component path in route

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/foundation#15]
If a route is found the first path of the component is added to the route [here](https://github.com/fuelphp/foundation/blob/master/src/Router.php#L150). IMO it is bad, since it cannot be determined (if the namespace points to multiple directories) which is the current on.

The route should probably contain all the paths or none of them, since the path is available from the component which is available in the request. I feel a bit of redundacy here, but I can live with that.

**Comment by stevewest** [comment]
Closing because of foundation rewrite.
