### ISSUE TITLE
Move proxies to a separate package

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/foundation#18]
Proxies make the package less maintainable. @WanWizard are you fine with that?

**Comment by WanWizard** [comment]
Agreed. Static interfaces should be part of a separate BC package. Since the framework itself doesn't do anything static anymore, it is only confusing to have them here.

**Comment by sagikazarmark** [comment]
Package name: bc, proxy, legacy? Oviously it can be a generic legacy package as well, or just a separated proxy package

**Comment by stevewest** [comment]
I'd vote for `legacy` to make it clear what it is.

**Comment by WanWizard** [comment]
2 - 0 !

**Comment by sagikazarmark** [comment]
Great, working on it.

**Comment by stevewest** [comment]
@sagikazarmark Do you think it would be useful to have travis/scrutinizer for it? If so I can add them for you.

**Comment by sagikazarmark** [comment]
For consistency: yeah.

But I won't add tests for proxies (for now). ;)

Packagist will be needed when I push the first commit, because (unfortunately) foundation relies on proxies somewhere deep in the code.

**Comment by stevewest** [comment]
Ok, I'll just add to packagist for now then once you have pushed the `compoer.json` and we can always add CI after.
