### ISSUE TITLE
Remove injection factory

### ISSUE THREAD

**Issue by sagikazarmark** [fuelphp/foundation#20]
We have been talking about this for a while now, so I am opening an issue: Injection factory is a ServiceLocator, thus it is an anti-pattern and should be removed. The main reason against it: some components must be created inside application initialization, because it relies on some configuration.

Possible solution: move these configurations out of the usual application configurations.

For example: session auto start and auto save should be moved to application parameters, out of the usual session config. This way such configuration can be done separately without relying on any configuration initialization. With other words, these application parameters should be configured outside of the application. Then the application itself can be initialized without such service locator

**Comment by stevewest** [comment]
Closing because of foundation rewrite.
