### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by Delpfine** [fuelphp/foundation#21]
Fatal error: Call to undefined method Whoops\Handler\JsonResponseHandler::onlyForAjaxRequests() in /home/delpfine/Projects/fuelphp/vendor/fuelphp/foundation/src/Error.php on line 215

1	0.0001	227592	{main}( )	.../index.php:0
2	0.0011	277064	Fuel\Foundation\Fuel::forge( )	.../index.php:46
3	0.0011	277536	Fuel\Foundation\Fuel::initialize( )	.../Fuel.php:170
4	0.0043	320856	Fuel\Foundation\Error->__construct( )	.../Fuel.php:68
5	0.0043	321512	Fuel\Foundation\Error->interactiveHandler( )	.../Error.php:59

Runing on  php-5.5.9 built-in server

**Comment by WanWizard** [comment]
Quite possible, this code hasn't even reached alpha state yet.

Have you run a composer install (or update), and is whoops installed?

**Comment by Delpfine** [comment]
git clone https://github.com/fuelphp/fuelphp.git
composer install

**Comment by WanWizard** [comment]
whoops is installed, so I can only assume something in their API has changed.

**Comment by kenjis** [comment]
It seems https://github.com/filp/whoops/commit/26f3dba7b5596403611f7a792dd54213bccd7968

**Comment by WanWizard** [comment]
Think I fixed it. Used github editing, no develop environment handy, so I couldn't test it.

**Comment by kenjis** [comment]
@WanWizard Sorry, the API is also out of dated.
I'll send PR.

**Comment by kenjis** [comment]
See #22 for Whoops 1.x.

See #23 for Whoops 2.0. But it does not work fine.

**Comment by stevewest** [comment]
Closing because of foundation rewrite.
