### ISSUE TITLE
Lang pluralisation

### ISSUE THREAD

**Issue by WanWizard** [fuelphp/foundation#5]
It would be handy if Lang would get more gettext alike features. For example

```
// array('result => 'total: {count|0:no results|1:one result|%d results}'):

echo \Lang::get('result', array('count' => 0)); // echo "no results"
echo \Lang::get('result', array('count' => 1)); // echo "one result"
echo \Lang::get('result', array('count' => 2)); // echo "2 results"
```

syntax is an example, it should be worked out what is best. It should not slow down language string parsing that doesn't contain this syntax.

**Comment by stevewest** [comment]
Closing this as it's not a foundation related feature.
